### ISSUE TITLE
Customizing the transformation

### ISSUE THREAD

**Issue by curioustechizen** [txusballesteros/android-transformer#2]
This is a great library and it comes just in time for a project I am getting started on. Would you considering adding the ability to customize the transformation? By customization I mean performing additional operations on some fields rather than mapping them one to one.

 Examples of where this would be useful:
- Mapping from an enum in the model to a String in the domain and vice-versa
- Converting from Lists in the model to foreign key relationships in the entity and vice-versa
- Performing validations/enforcing limits
- Taking a password from model and hashing it with a salt before saving in entity

**Comment by mradzinski** [comment]
+1 on this. Currently I'm working on an application that reacts differently to the network connection type. For example, if the actual network connection is WiFi it loads a high-res image, if it's mobile (3g, H, lte...) it loads a low-res image to preserver bandwidth. Sadly I cannot modify any fields in the POJO's since they interact with other parts of the application, so, If this library had an interceptor or something in between the model conversion and the final result were I could make the network check and modify my final model, then I would use it without thinking about it.

**Comment by txusballesteros** [comment]
Hi guys,

I'm working on this feature, and I think that I will can release that the next week. :bowtie:

**Comment by txusballesteros** [comment]
Hi guys, you can use this new feature with version 1.1
